name: glofrim_exp

channels:
  - conda-forge

dependencies:
  - python=2.7
  - numpy==1.14.5
  - netcdf4>=1.3.1
  - rasterio>=1.0
  - rtree>=0.8.3
  - click>=6.7
  - configparser>=3.5.0
  - python-dateutil>=2.2
  - pytz>=2014.3
  - faulthandler>=2.3
  - six>=1.6.1
  - pip>=9.0.3
  - matplotlib
  - cartopy
  - pandas
  - pip:
    - bmi-python
    - git+https://github.com/openearth/glofrim.git@2.0-beta
    - 